set_property SRC_FILE_INFO {cfile:C:/master/Embedded/borrar/Assignment_2/EmbeddedSystem_labs/AS03/AS03.srcs/constrs_1/imports/lab1/lab1_zybo.xdc rfile:../../../AS03.srcs/constrs_1/imports/lab1/lab1_zybo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN Y16 [get_ports btn_tri_io]
set_property src_info {type:XDC file:1 line:5 export:INPUT save:INPUT read:READ} [current_design]
set_property IOSTANDARD LVCMOS33 [get_ports btn_tri_io]
